extends:
    - stylelint-config-standard
    - stylelint-config-recommended-vue
plugins:
    - stylelint-use-nesting
rules:
    color-function-notation: modern
    selector-nested-pattern: '&'
    no-empty-source: null
    csstools/use-nesting: true
    "selector-class-pattern": [
        "^([a-z][a-z0-9]*)(-[a-z0-9]+)*(--[a-z0-9 -]+)?$",
        {
        "message": "Expected class selector to be kebab-case or BEM (with --modifier)"
        }
    ]